### ISSUE TITLE
pdf

### ISSUE THREAD

**Issue by csmiguel** [PoisotLab/manuscript-template#11]
The `gh-pages` is created perfectly, however I cannot find the PDF. Where is it stored?

**Comment by tpoisot** [comment]
There are a couple options:

1. you can navigate to the `gh-pages` branches, the PDFs will be here ([draft](https://github.com/csmiguel/marsh_metabarcoding_manuscript/blob/gh-pages/draft.pdf) and [preprint](https://github.com/csmiguel/marsh_metabarcoding_manuscript/blob/gh-pages/preprint.pdf))
2. you can access the HTML version at https://csmiguel.github.io/marsh_metabarcoding_manuscript/, and the links to the PDFs will be right below the abstract:

![Screenshot from 2021-09-15 09-56-49](https://user-images.githubusercontent.com/579329/133447134-a006b41d-3621-46ef-bb88-add45157ecb4.png)
