### ISSUE TITLE
Abstracts not rendering 

### ISSUE THREAD

**Issue by TanyaS08** [PoisotLab/manuscript-template#15]
The new template seems to not be including abstracts across the board (.html, preprint .pdf, and draft .pdf).

See screenshot below directly from the template ms preprint .pdf

<img width="1344" alt="Screenshot 2022-10-31 at 15 35 17" src="https://user-images.githubusercontent.com/61696728/199020449-4f28b60c-1713-4841-9172-1792ad2e13c5.png">

**Comment by TanyaS08** [comment]
Edit: looks like the glyphs used as superscripts with the authors is also not having a good time? So might be a bigger metadata file incorporation issue?

**Comment by tpoisot** [comment]
Yeahm I know and I kinda know why, and I will fix it in the not too distant future - by Friday!

**Comment by TanyaS08** [comment]
🫡🫡🫡
